### ISSUE TITLE
WinOS: 'os' has no attribute 'mknod', no module named 'cv2' || original title"跑不通咋办"

### ISSUE THREAD

**Issue by birdfine** [Yonv1943/ElegantRL#7]
兄弟你这介绍的好像不太详细呀，而且有的程序导入的包都不见了，请问有没有更好的版本？

**Comment by Yonv1943** [comment]
我会检查，没有bug后的程序会出现在此repo的根目录。
而最新的版本在 BetaWarning里。

你描述“有的程序导入的包都不见了”，**我没有观察到此现象。这个RL库只需要 PyTorch 这个第三方库**。
这个RL库核心程序只有3个 `AgentRun.py   AgentZoo.py    AgentNet.py` 除此以外，其他皆非必要。

 `AgentRun.py` 可以引导你Run这个库。你可以根据你的需要下载 RL env。例如 `gym, box2d-py, py-bullet, ... 甚至你自己编写的符合gym标准的环境`。 我在ReadMe 文件中都做了引导。

**Comment by birdfine** [comment]
感谢感谢，我刚上手，没准是我太菜了，我再多试试，谢谢你的帮助！

**Comment by birdfine** [comment]
![image](https://user-images.githubusercontent.com/49951200/95674639-16543b00-0be4-11eb-84f7-4c095f6b9f0b.png)

**Comment by birdfine** [comment]
![Uploading image.png…]()

**Comment by birdfine** [comment]
![image](https://user-images.githubusercontent.com/49951200/95674739-d5105b00-0be4-11eb-9c9a-15c3775e06e3.png)

**Comment by Yonv1943** [comment]
![image](https://user-images.githubusercontent.com/49951200/95674639-16543b00-0be4-11eb-84f7-4c095f6b9f0b.png)

You can comment out this line of code about 'cv2'. Or run `pip install opencv-python` (CV: compute vision, image)
你可以直接注释掉使用了 cv2 这个库的代码，它不是必要的。或者直接运行  `pip install opencv-python` 把这个库安装了。这是一个用来处理图像的库。


![image](https://user-images.githubusercontent.com/49951200/95674739-d5105b00-0be4-11eb-9c9a-15c3775e06e3.png)

You can comment out this line of code about `os.mknod`. Or change `os.nod` to `os.mkfifo` in WindowOS.
你可以直接注释掉使用了 cv2 这个库的代码，它不是必要的。或者直接在Window系统里面把 `os.nod` 改成 `os.mkfifo`.
这一行代码是用来保存训练进度，方便我自己查看。我可能会在下一次更新修复这个兼容问题。

Thanks. 感谢你的反馈。

**Comment by birdfine** [comment]
Thank you so much！

**Comment by Yonv1943** [comment]
I have resolved this issue. I directly removed ʻos.mknod` from the code. This question will be closed.
我已经解决此问题。我直接将 `os.mknod` 从代码中移除。此问题将被关闭

**Comment by Yonv1943** [comment]
I have resolved this issue. I directly removed `os.mknod` from the code. This question will be closed. 

我已经解决此问题。我直接将 `os.mknod` 从代码中移除。此问题将被关闭
