### ISSUE TITLE
YonV: Don't open Issues like this 不建议像这样开问题 → __init__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by birdfine** [Yonv1943/ElegantRL#8]
![image](https://user-images.githubusercontent.com/49951200/95863696-13e61280-0d97-11eb-9078-0e8b7d1d468b.png)
![image](https://user-images.githubusercontent.com/49951200/95863904-514aa000-0d97-11eb-8e4c-eaf38abe98ec.png)
Thank you!

**Comment by birdfine** [comment]
![Uploading image.png…]()

**Comment by birdfine** [comment]
![image](https://user-images.githubusercontent.com/49951200/95864698-59efa600-0d98-11eb-94e2-2de0970d3544.png)

**Comment by birdfine** [comment]
![image](https://user-images.githubusercontent.com/49951200/95864760-7095fd00-0d98-11eb-825f-57567beb650c.png)

**Comment by Yonv1943** [comment]
`Argument()          __init__() takes 1 positional argument but 2 were given`
`args = Arguments(rl_agent=Zoo.AgentModSAC, env_name="LunarLanderContinuous-v2", gpu_id=None)`

I had update `Argument()`. 我已经对`Argument()`进行更新。修复了此问题。
If you want to run on CPU. You just let `gpu_id=None`. 若你想要用CPU运行，那么让`gpu_id=None`。

---
`DiscreteSAC` had change to `DiscreteGAE`.
`DiscreteSAC` 已经被我改成了 `DiscreteGAE`. 原先的命名是错误的，已被我改正。

Try the following: 试一试下面这些：
```
def run__discrete_action(gpu_id=None):
    import AgentZoo as Zoo
    """online policy"""  # plan to check args.max_total_step
    args = Arguments(rl_agent=Zoo.AgentDiscreteGAE, gpu_id=gpu_id)
```
You will get: 你的终端会得到：
```
| GPU: 1 | CWD: ./AgentDiscreteGAE/CartPole-v0_1
| Remove
GPU      Step      MaxR |    avgR      stdR |    ExpR     LossA     LossC
1    1.03e+03    114.50 |
1    5.16e+03    145.44 |
1    6.25e+03    148.62 |
1    7.29e+03    172.31 |
1    8.40e+03    199.38 |
GPU      Step   TargetR |    avgR      stdR |    ExpR  UsedTime  ########
1    8.40e+03    195.00 |  199.38      2.42 |   89.00        22  ########
```

**Comment by Yonv1943** [comment]
YonV: Don't open Issues like this 不建议像这样开问题 → __init__() takes 1 positional argument but 2 were given

The reason why error occurred: Did not read the `ReadMe.md` file, did not refer to the examples in `run__demo(), run__xxx()`. 产生以下↓这个问题的原因是：没有阅读 ReadMe.md 文件，没有参考 `run__demo(), run__xxx()` 提供的示例。
`Argument() __init__() takes 1 positional argument but 2 were given`
